name: Cypress Tests

on: 
  pull_request:
  push:

     branches:    
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18, 19, 20]
    name: E2E on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v3
           
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
         
      - name: Test Artifacts
        uses: actions/upload-artifact@v3

        if: failure()
        with:
         name: cypress-screenshots
         path: ./cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
         name: cypress-videos
         path: ./cypress/videos

    continue-on-error: true